### ISSUE TITLE
Generator is not case sensitive to given regular expression.

### ISSUE THREAD

**Issue by JanDrabik** [Schwusch/randexp.dart#1]
Steps to reproduce:
```dart
RandExp(RegExp(r'([A-Z0-9]\w{6})')).gen();
// returns VPrc5ai instead of VPRC5AI
```

Cheers

**Comment by Schwusch** [comment]
Hi, and thanks for reporting an issue!
I ran your example a few times, and checked with [Regexper](https://regexper.com/#%28%5BA-Z0-9%5D%5Cw%7B6%7D%29).
The  `r'([A-Z0-9]\w{6})'` regex is supposed to generate one character that is between A-Z or 0-9, followed by 6 `word`s, and it seems like it does just that.
In order to get your desired output, `r'([A-Z0-9]{7})'` seems to work better.

Cheers
